### ISSUE TITLE
better to use multiline

### ISSUE THREAD

**Issue by tallinn-learning** [JacquelineT01/Homework-04#1]
https://github.com/JacquelineT01/Homework-04/blob/603345e313d703d4f807a55ed2bcd2a140b0ae3b/src/Calculator.java#L2C2-L3C78

Multi-Line Method:

public int addition(int num1, int num2) { 
    return num1 + num2; 
}

Easier to read, especially for developers unfamiliar with the code.

**Comment by JacquelineT01** [comment]
Changes applied
