### ISSUE TITLE
minor changes

### ISSUE THREAD

**Issue by tallinn-learning** [JacquelineT01/Homework-04#2]
https://github.com/JacquelineT01/Homework-04/blob/603345e313d703d4f807a55ed2bcd2a140b0ae3b/src/NumberManipulator.java#L2C4-L5C20

Indentation: Each method is indented to clearly show the block of code inside the method. This makes it easy to identify where the method starts and ends.

Whitespace: Adding a blank line between methods also enhances readability by visually separating different methods.

**Comment by JacquelineT01** [comment]
Changes applied
